Small fixes to intro and golang tutorial
libopenstorage/libopenstorage.github.io pull request #3
Opened 2018-11-27 18:18 UTC by ggriffiths

- state that this tutorial uses polyglot 1.x.x (2.x.x has a little different structure for sending requests - I downloaded that version first and had issues). Alternatively we could change the example to use the polyglot 2.x.x API
- update route /v1/clusters/current -> /v1/clusters/inspectcurrent 
- add `go get` commands for dependencies 
- add a few comments to top of code snippets  
- fix compile error w/ taskId

2018-11-27 19:05 UTC, lpabon requested changes

2018-11-27 19:05 UTC, lpabon commented on docs/tutorial-golang.md
> +```
This is good for simplicity. Move the recorded demo to this section and explain to use that for production.

2018-11-27 21:38 UTC, ggriffiths commented
@lpabon moved the recorded demo section to be after the `imports` and `get get` sections!

2018-11-28 18:00 UTC, ggriffiths commented
rebased your commit from master - seems like the `w/` directory likes to cause merge conflicts

2018-11-28 21:34 UTC, lpabon approved these changes

2018-11-28 21:34 UTC, merged